### ISSUE TITLE
Not able to open pages under hierarchy

### ISSUE THREAD

**Issue by AvijeetPrasad** [rebornix/logseq-open-in-code#3]
Hi,

Thanks for this very useful plugin. I often use the plugin to `Edit current page` and currently it is able to open only those pages which are not under hierarchy.

For example, As on version `0.6.9` of Logseq, a page `Projects/Meetings.md` is saved as `Projects%2FMeetings.md`on disc, while the plugins tries to search for `Projects/Meetings.md` itself and cannot find it.

So, I guess, we need to replace `/` with `%2F` when opening such pages.

**Comment by icarus4** [comment]
+1
Anyway, very happy to find this plugin 😃

**Comment by rebornix** [comment]
@AvijeetPrasad  @icarus4 thank you both for the feedback, it should now be fixed in 0.0.5
