### ISSUE TITLE
Support for VSCodium

### ISSUE THREAD

**Issue by jpjpjp** [rebornix/logseq-open-in-code#4]
Any chance to add a configuration option to support [VSCodium: 100% Open Source Version of Microsoft VS Code](https://itsfoss.com/vscodium/)?

The cmd line shortcut for for VSCode is `code`.   It's `codium` for VSCodium

**Comment by rebornix** [comment]
0.0.7 has the fix released, thanks!

**Comment by jpjpjp** [comment]
Thanks @rebornix !   Just tested and it works.

FWIW, the "Always in new window" setting is not obeyed when the URL Scheme is set to VS Codium.

Its not a problem for me, but if you need a tester I'd be happy to try again with a new version.
