### ISSUE TITLE
Path does not exist

### ISSUE THREAD

**Issue by nikhilmaddirala** [rebornix/logseq-open-in-code#7]
Hi, I'm getting this error when trying to open current page (titled "logseq-gtd") in VS Code
<img width="261" alt="image" src="https://user-images.githubusercontent.com/4138581/230440004-9b1bc636-bcff-4bc7-af86-40c0d0ec8e89.png">

**Comment by adxsoft** [comment]
Same for me on Mac 0.9.1 version

**Comment by rebornix** [comment]
It seems like a breaking change from logseq. I'll take a look

**Comment by compadrejunior** [comment]
Same problem here in Windows 11.

**Comment by mrdavidlaing** [comment]
Same for me, with versions:

Open in VS Code: v0.0.5
OS: Mac OS 13.4 (22F66)
Logseq: 0.9.8 (0.9.8)
VS Code: 1.78.2 (Universal)

## What happens
Whilst all the other menu options work, when I try the "Edit current page" option
![image](https://github.com/KerfuffleV2/logseq-plugin-interval-hints/assets/227505/57467456-2609-46e0-be53-a25916fd8db8)

VS Code opens showing the following error:

![image](https://github.com/KerfuffleV2/logseq-plugin-interval-hints/assets/227505/3242a965-9efc-43f9-ac6f-8b770b7a1cda)

## What I expect to happen
The current page is opened in VSCode without an error

## Ideas
It looks like its trying to open an absolute path - `/pages/Note.md` without including the full path to the graph folder.

**Comment by adxsoft** [comment]
Unfortunately this issue (a showstopper) is still not working after several months despite a PR with the fix being submitted.
I understand the developer probably is busy but it would be appreciated by many logseq users if the PR could be integrated and the plugin re-issued.

This is such a useful plugin and its a shame not to be able to use it anymore.

TIA

**Comment by mrdavidlaing** [comment]
FWIW, you can manually patch the fix from https://github.com/rebornix/logseq-open-in-code/pull/8 into  `~/.logseq/plugins/logseq-open-in-code/dist/assets/index.64104ec8.js` by replacing:

```
async function Ai(e){const t=await logseq.DB.datascriptQuery(`[:find ?file
                :where
                [?b :file/path ?file]
                [(== ?b ${e})]
            ]`);return t&&t.length>0?t[0][0]:null}
```
with 
```
async function Ai(e){const graph = await logseq.App.getCurrentGraph(); const t=await logseq.DB.datascriptQuery(`[:find ?file
                :where
                [?b :file/path ?file]
                [(== ?b ${e})]
            ]`);return t&&t.length>0?(graph.url.replace("logseq_local_", "") + "/" + t[0][0]):null}
```

Disable / enable the "Open in VS Code" plugin for the changes to have an effect

**Comment by adxsoft** [comment]
Thanks that works!

**Comment by sindoc** [comment]
@mrdavidlaing Thanks for patching it here. If we make the change, as you describe it here, will it be safe after the potential future updates?

**Comment by mrdavidlaing** [comment]
In theory the next time the plugin is updated this "manual" patch will just get overwritten.

**Comment by notuntoward** [comment]
> Hi, I'm getting this error when trying to open current page (titled "logseq-gtd") in VS Code <img alt="image" width="261" src="https://user-images.githubusercontent.com/4138581/230440004-9b1bc636-bcff-4bc7-af86-40c0d0ec8e89.png">

Still broken in mid July.  Windows 11.

**Comment by e-zz** [comment]
Hey guys, I just published a patched release [here](https://github.com/e-zz/logseq-open-in-code/releases/tag/0.0.6).
Now you could manually reload from logseq the content in the released zip file to make it work.

And I also added two shortcuts for editting pages or graph folder in vscode. Check the plugin setting and change these shortcuts if you want.

**Comment by rebornix** [comment]
Fixed now via https://github.com/rebornix/logseq-open-in-code/pull/9

**Comment by rebornix** [comment]
0.0.7 has the fix released, thanks!
